# Generated by Django 4.2.7 on 2025-11-04 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_visit_date', models.DateField(verbose_name='Fecha primera visita')),
                ('last_visit_date', models.DateField(verbose_name='Fecha última visita')),
                ('total_visits', models.PositiveIntegerField(default=1, verbose_name='Total de visitas')),
                ('clinic_name', models.CharField(max_length=200, verbose_name='Nombre del consultorio')),
                ('clinic_address', models.TextField(verbose_name='Dirección del consultorio')),
                ('clinic_phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono del consultorio')),
                ('specialty_visited', models.CharField(max_length=100, verbose_name='Especialidad visitada')),
                ('rating', models.PositiveIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Calificación (1-5)')),
                ('patient_notes', models.TextField(blank=True, verbose_name='Notas del paciente')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(limit_choices_to={'user_type': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='clinic_visits', to=settings.AUTH_USER_MODEL, verbose_name='Paciente')),
                ('professional', models.ForeignKey(limit_choices_to={'user_type': 'professional'}, on_delete=django.db.models.deletion.CASCADE, related_name='patient_visits', to=settings.AUTH_USER_MODEL, verbose_name='Profesional')),
            ],
            options={
                'verbose_name': 'Visita a Consultorio',
                'verbose_name_plural': 'Historial de Consultorios Visitados',
                'ordering': ['-last_visit_date'],
                'unique_together': {('patient', 'professional')},
            },
        ),
    ]
